"""add user hearts and xp

Revision ID: 94bc8c90a880
Revises: 802d648d3434
Create Date: 2026-09-16 17:56:14.260805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bc8c90a880'
down_revision: Union[str, Sequence[str], None] = '802d648d3434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hearts', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_heart_lost_at', sa.DateTime(timezone=True), nullable=True))

    op.alter_column('users', 'hearts', server_default=None)
    op.alter_column('users', 'xp', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_heart_lost_at')
    op.drop_column('users', 'xp')
    op.drop_column('users', 'hearts')
    # ### end Alembic commands ###
