"""add conversation mistake tracking

Revision ID: dadcca0e4a23
Revises: 94bc8c90a880
Create Date: 2026-09-16 19:01:13.735263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadcca0e4a23'
down_revision: Union[str, Sequence[str], None] = '94bc8c90a880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column(
        'had_mistake', 
        sa.Boolean(), 
        nullable=False,
        server_default=sa.false(),
        ),
    )
    op.alter_column('conversations', 'had_mistake', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'had_mistake')
    # ### end Alembic commands ###
